name: Extract and Release

on:
    workflow_dispatch:
        inputs:
            ROM_URL:
                description: "URL to ROM file"
                required: true
            DEVICE_NAME:
                description: "Device name"
                required: true
            EXTRACTED_FILES:
                description: "Files to extract and upload"
                required: true

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download file
              run: |
                  echo "Downloading ROM from: ${{ github.event.inputs.ROM_URL }}"
                  curl -LJO "${{ github.event.inputs.ROM_URL }}" || {
                    echo "::error:: Failed to download file";
                    exit 1;
                  }
                  ls -lh

            - name: Extract Payload
              run: |
                  ZIP_FILE=$(ls *.zip 2>/dev/null | head -n 1)
                  if [ -z "$ZIP_FILE" ]; then
                    echo "::error:: No ZIP file found after download"
                    exit 1
                  fi

                  chmod u+x .github/scripts/android-ota-extractor
                  .github/scripts/android-ota-extractor "$ZIP_FILE"

                  echo "ZIP_FILE=$ZIP_FILE" >> $GITHUB_ENV
                  echo "ZIP_FILE_SHA256=$(sha256sum "$ZIP_FILE" | cut -d' ' -f1)" >> $GITHUB_ENV

                  large_files=$(find . -maxdepth 1 -type f -size +2G)
                  if [ -n "$large_files" ]; then
                    echo "::warning:: The following files are larger than 2 GB and will not be uploaded:"
                    for file in $large_files; do
                      echo "$file ($(du -h "$file" | awk '{print $1}'))"
                    done
                  fi

            - name: Validate Extracted Files
              run: |
                  for file in $(echo "${{ github.event.inputs.EXTRACTED_FILES }}" | tr ',' ' '); do
                    if [ ! -f "$file" ]; then
                      echo "::error:: File $file not found!"
                      exit 1
                    fi
                  done

            - name: Upload to Release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  files: ${{ github.event.inputs.EXTRACTED_FILES }}
                  name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
                  tag_name: ${{ github.run_id }}
                  body: |
                      Device: ${{ github.event.inputs.DEVICE_NAME }}
                      Filename: [${{ env.ZIP_FILE }}](${{ github.event.inputs.ROM_URL }})
                      Extracted files: ${{ github.event.inputs.EXTRACTED_FILES }}
                      SHA256: ${{ env.ZIP_FILE_SHA256 }}
